// GXQS WalletService — API contract for the Wallet application.
//
// The Wallet is a consumer of Core's authority.  It may submit transactions
// to the mempool and query chain state, but it does NOT participate in
// consensus and does NOT define its own protocol types.
// "Read-only with respect to consensus" means the Wallet has no block
// production or validator authority; it can only observe and submit.
//
// All types used here are imported from the canonical schemas in the parent
// directory.  The Wallet MUST NOT redefine these types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: services/wallet.proto

package gxqsservices

import (
	corepb "github.com/gxqs/wallet/runtime/protocol/go-rpc-bridge/internal/corepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubmitTransactionRequest wraps a signed transaction for mempool submission.
type SubmitTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *corepb.Transaction    `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
	mi := &file_services_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_services_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTransactionRequest) GetTransaction() *corepb.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// SubmitTransactionResponse is returned after a transaction is received.
// accepted is true if the transaction was accepted into the mempool.
type SubmitTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tx_id is the SHA3-256 hash of the transaction (32 bytes).
	TxId     []byte `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Accepted bool   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// error contains a human-readable rejection reason when accepted is false.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionResponse) Reset() {
	*x = SubmitTransactionResponse{}
	mi := &file_services_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionResponse) ProtoMessage() {}

func (x *SubmitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_services_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTransactionResponse) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

func (x *SubmitTransactionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitTransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetAccountStateRequest identifies an account by its 32-byte address.
type GetAccountStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountStateRequest) Reset() {
	*x = GetAccountStateRequest{}
	mi := &file_services_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStateRequest) ProtoMessage() {}

func (x *GetAccountStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStateRequest.ProtoReflect.Descriptor instead.
func (*GetAccountStateRequest) Descriptor() ([]byte, []int) {
	return file_services_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountStateRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

// GetAccountStateResponse carries the on-chain state of an account.
type GetAccountStateResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Nonce   uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Balance uint64                 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	// code_hash is the SHA3-256 of contract bytecode, or zero for EOAs (32 bytes).
	CodeHash []byte `protobuf:"bytes,3,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	// storage_root is the Merkle root of contract storage (32 bytes).
	StorageRoot   []byte `protobuf:"bytes,4,opt,name=storage_root,json=storageRoot,proto3" json:"storage_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountStateResponse) Reset() {
	*x = GetAccountStateResponse{}
	mi := &file_services_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStateResponse) ProtoMessage() {}

func (x *GetAccountStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStateResponse.ProtoReflect.Descriptor instead.
func (*GetAccountStateResponse) Descriptor() ([]byte, []int) {
	return file_services_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountStateResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *GetAccountStateResponse) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetAccountStateResponse) GetCodeHash() []byte {
	if x != nil {
		return x.CodeHash
	}
	return nil
}

func (x *GetAccountStateResponse) GetStorageRoot() []byte {
	if x != nil {
		return x.StorageRoot
	}
	return nil
}

// GetBlockRequest selects a block by height OR by block ID (hash).
// Exactly one of height or block_id should be set.
type GetBlockRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Height uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// block_id is a 32-byte SHA3-256 block hash.  When non-empty, height is
	// ignored and the node performs a hash-based lookup.
	BlockId       []byte `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_services_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_services_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlockRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GetBlockRequest) GetBlockId() []byte {
	if x != nil {
		return x.BlockId
	}
	return nil
}

// GetBlockResponse wraps the requested block.  found is false when the block
// does not exist at the requested height or hash.
type GetBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *corepb.Block          `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_services_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_services_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *GetBlockResponse) GetBlock() *corepb.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *GetBlockResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// GetTransactionRequest looks up a transaction by its 32-byte ID.
type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          []byte                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_services_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_services_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionRequest) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

// GetTransactionResponse wraps the requested transaction and its inclusion
// information.
type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *corepb.Transaction    `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	BlockHeight   uint64                 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_services_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_services_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionResponse) GetTransaction() *corepb.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *GetTransactionResponse) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *GetTransactionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// StreamEventsRequest configures a server-sent event stream.
type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// from_height is the block height from which to start streaming.
	// Use 0 to start from the current tip.
	FromHeight uint64 `protobuf:"varint,1,opt,name=from_height,json=fromHeight,proto3" json:"from_height,omitempty"`
	// event_types filters the stream to the specified event type strings.
	// An empty list means "all events".
	EventTypes    []string `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_services_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_services_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *StreamEventsRequest) GetFromHeight() uint64 {
	if x != nil {
		return x.FromHeight
	}
	return 0
}

func (x *StreamEventsRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

// ChainEvent is a single item in the real-time event stream.
type ChainEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventType string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Height    uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// payload is a serialized event-specific message (scheme-defined).
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// timestamp is the Unix millisecond time at which the event was emitted.
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// event_hash is the SHA3-256 hash that chains this event to its predecessor.
	EventHash     []byte `protobuf:"bytes,5,opt,name=event_hash,json=eventHash,proto3" json:"event_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainEvent) Reset() {
	*x = ChainEvent{}
	mi := &file_services_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainEvent) ProtoMessage() {}

func (x *ChainEvent) ProtoReflect() protoreflect.Message {
	mi := &file_services_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainEvent.ProtoReflect.Descriptor instead.
func (*ChainEvent) Descriptor() ([]byte, []int) {
	return file_services_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *ChainEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ChainEvent) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ChainEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChainEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChainEvent) GetEventHash() []byte {
	if x != nil {
		return x.EventHash
	}
	return nil
}

var File_services_wallet_proto protoreflect.FileDescriptor

const file_services_wallet_proto_rawDesc = "" +
	"\n" +
	"\x15services/wallet.proto\x12\x10gxqs.v1.services\x1a\x11transaction.proto\x1a\vblock.proto\"R\n" +
	"\x18SubmitTransactionRequest\x126\n" +
	"\vtransaction\x18\x01 \x01(\v2\x14.gxqs.v1.TransactionR\vtransaction\"b\n" +
	"\x19SubmitTransactionResponse\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\fR\x04txId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"2\n" +
	"\x16GetAccountStateRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\"\x89\x01\n" +
	"\x17GetAccountStateResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x04R\abalance\x12\x1b\n" +
	"\tcode_hash\x18\x03 \x01(\fR\bcodeHash\x12!\n" +
	"\fstorage_root\x18\x04 \x01(\fR\vstorageRoot\"D\n" +
	"\x0fGetBlockRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\fR\ablockId\"N\n" +
	"\x10GetBlockResponse\x12$\n" +
	"\x05block\x18\x01 \x01(\v2\x0e.gxqs.v1.BlockR\x05block\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\",\n" +
	"\x15GetTransactionRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\fR\x04txId\"\x89\x01\n" +
	"\x16GetTransactionResponse\x126\n" +
	"\vtransaction\x18\x01 \x01(\v2\x14.gxqs.v1.TransactionR\vtransaction\x12!\n" +
	"\fblock_height\x18\x02 \x01(\x04R\vblockHeight\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"W\n" +
	"\x13StreamEventsRequest\x12\x1f\n" +
	"\vfrom_height\x18\x01 \x01(\x04R\n" +
	"fromHeight\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\"\x9a\x01\n" +
	"\n" +
	"ChainEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_hash\x18\x05 \x01(\fR\teventHash2\xf4\x03\n" +
	"\rWalletService\x12l\n" +
	"\x11SubmitTransaction\x12*.gxqs.v1.services.SubmitTransactionRequest\x1a+.gxqs.v1.services.SubmitTransactionResponse\x12f\n" +
	"\x0fGetAccountState\x12(.gxqs.v1.services.GetAccountStateRequest\x1a).gxqs.v1.services.GetAccountStateResponse\x12Q\n" +
	"\bGetBlock\x12!.gxqs.v1.services.GetBlockRequest\x1a\".gxqs.v1.services.GetBlockResponse\x12c\n" +
	"\x0eGetTransaction\x12'.gxqs.v1.services.GetTransactionRequest\x1a(.gxqs.v1.services.GetTransactionResponse\x12U\n" +
	"\fStreamEvents\x12%.gxqs.v1.services.StreamEventsRequest\x1a\x1c.gxqs.v1.services.ChainEvent0\x01B9Z7github.com/gxqs/core/proto/gen/v1/services;gxqsservicesb\x06proto3"

var (
	file_services_wallet_proto_rawDescOnce sync.Once
	file_services_wallet_proto_rawDescData []byte
)

func file_services_wallet_proto_rawDescGZIP() []byte {
	file_services_wallet_proto_rawDescOnce.Do(func() {
		file_services_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_wallet_proto_rawDesc), len(file_services_wallet_proto_rawDesc)))
	})
	return file_services_wallet_proto_rawDescData
}

var file_services_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_services_wallet_proto_goTypes = []any{
	(*SubmitTransactionRequest)(nil),  // 0: gxqs.v1.services.SubmitTransactionRequest
	(*SubmitTransactionResponse)(nil), // 1: gxqs.v1.services.SubmitTransactionResponse
	(*GetAccountStateRequest)(nil),    // 2: gxqs.v1.services.GetAccountStateRequest
	(*GetAccountStateResponse)(nil),   // 3: gxqs.v1.services.GetAccountStateResponse
	(*GetBlockRequest)(nil),           // 4: gxqs.v1.services.GetBlockRequest
	(*GetBlockResponse)(nil),          // 5: gxqs.v1.services.GetBlockResponse
	(*GetTransactionRequest)(nil),     // 6: gxqs.v1.services.GetTransactionRequest
	(*GetTransactionResponse)(nil),    // 7: gxqs.v1.services.GetTransactionResponse
	(*StreamEventsRequest)(nil),       // 8: gxqs.v1.services.StreamEventsRequest
	(*ChainEvent)(nil),                // 9: gxqs.v1.services.ChainEvent
	(*corepb.Transaction)(nil),        // 10: gxqs.v1.Transaction
	(*corepb.Block)(nil),              // 11: gxqs.v1.Block
}
var file_services_wallet_proto_depIdxs = []int32{
	10, // 0: gxqs.v1.services.SubmitTransactionRequest.transaction:type_name -> gxqs.v1.Transaction
	11, // 1: gxqs.v1.services.GetBlockResponse.block:type_name -> gxqs.v1.Block
	10, // 2: gxqs.v1.services.GetTransactionResponse.transaction:type_name -> gxqs.v1.Transaction
	0,  // 3: gxqs.v1.services.WalletService.SubmitTransaction:input_type -> gxqs.v1.services.SubmitTransactionRequest
	2,  // 4: gxqs.v1.services.WalletService.GetAccountState:input_type -> gxqs.v1.services.GetAccountStateRequest
	4,  // 5: gxqs.v1.services.WalletService.GetBlock:input_type -> gxqs.v1.services.GetBlockRequest
	6,  // 6: gxqs.v1.services.WalletService.GetTransaction:input_type -> gxqs.v1.services.GetTransactionRequest
	8,  // 7: gxqs.v1.services.WalletService.StreamEvents:input_type -> gxqs.v1.services.StreamEventsRequest
	1,  // 8: gxqs.v1.services.WalletService.SubmitTransaction:output_type -> gxqs.v1.services.SubmitTransactionResponse
	3,  // 9: gxqs.v1.services.WalletService.GetAccountState:output_type -> gxqs.v1.services.GetAccountStateResponse
	5,  // 10: gxqs.v1.services.WalletService.GetBlock:output_type -> gxqs.v1.services.GetBlockResponse
	7,  // 11: gxqs.v1.services.WalletService.GetTransaction:output_type -> gxqs.v1.services.GetTransactionResponse
	9,  // 12: gxqs.v1.services.WalletService.StreamEvents:output_type -> gxqs.v1.services.ChainEvent
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_services_wallet_proto_init() }
func file_services_wallet_proto_init() {
	if File_services_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_wallet_proto_rawDesc), len(file_services_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_wallet_proto_goTypes,
		DependencyIndexes: file_services_wallet_proto_depIdxs,
		MessageInfos:      file_services_wallet_proto_msgTypes,
	}.Build()
	File_services_wallet_proto = out.File
	file_services_wallet_proto_goTypes = nil
	file_services_wallet_proto_depIdxs = nil
}
