// GXQS canonical block schema.
//
// This file is the SOURCE OF TRUTH for block and block-header wire format.
// Field numbers are permanent; see https://github.com/gxqs/core/tree/v0.1.0/proto for versioning rules.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: block.proto

package gxqsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockHeader contains the metadata for a GXQS block.
// The header ID is SHA3-256 of the deterministic serialization of all fields
// EXCEPT proposer_signature (which signs the ID).
type BlockHeader struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChainId uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Height  uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// parent_id is the SHA3-256 hash of the previous block header (32 bytes).
	ParentId []byte `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// state_root is the Merkle root of the world state after this block (32 bytes).
	StateRoot []byte `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	// tx_root is the Merkle root of all transactions in this block (32 bytes).
	TxRoot []byte `protobuf:"bytes,5,opt,name=tx_root,json=txRoot,proto3" json:"tx_root,omitempty"`
	// timestamp is a Unix millisecond timestamp.
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// proposer_address is the 32-byte address of the block proposer.
	ProposerAddress []byte `protobuf:"bytes,7,opt,name=proposer_address,json=proposerAddress,proto3" json:"proposer_address,omitempty"`
	// round is the BFT round in which this block was proposed.
	Round uint32 `protobuf:"varint,8,opt,name=round,proto3" json:"round,omitempty"`
	// proposer_signature is the proposer's PQC signature over the header ID.
	// It is NOT included in the header ID computation.
	ProposerSignature []byte `protobuf:"bytes,9,opt,name=proposer_signature,json=proposerSignature,proto3" json:"proposer_signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

func (x *BlockHeader) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *BlockHeader) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockHeader) GetParentId() []byte {
	if x != nil {
		return x.ParentId
	}
	return nil
}

func (x *BlockHeader) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BlockHeader) GetTxRoot() []byte {
	if x != nil {
		return x.TxRoot
	}
	return nil
}

func (x *BlockHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockHeader) GetProposerAddress() []byte {
	if x != nil {
		return x.ProposerAddress
	}
	return nil
}

func (x *BlockHeader) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *BlockHeader) GetProposerSignature() []byte {
	if x != nil {
		return x.ProposerSignature
	}
	return nil
}

// CommitVote is a validator's pre-commit vote for a block.
// Validators sign either pre_vote_payload() or pre_commit_payload() to prevent
// cross-phase signature replay.
type CommitVote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// validator_address is the 32-byte address of the signing validator.
	ValidatorAddress []byte `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// block_id is the SHA3-256 hash of the voted-for block header (32 bytes).
	BlockId       []byte        `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Height        uint64        `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Round         uint32        `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Sig           *PQCSignature `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitVote) Reset() {
	*x = CommitVote{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitVote) ProtoMessage() {}

func (x *CommitVote) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitVote.ProtoReflect.Descriptor instead.
func (*CommitVote) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *CommitVote) GetValidatorAddress() []byte {
	if x != nil {
		return x.ValidatorAddress
	}
	return nil
}

func (x *CommitVote) GetBlockId() []byte {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *CommitVote) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CommitVote) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CommitVote) GetSig() *PQCSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

// Block is a complete GXQS block.
type Block struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Header       *BlockHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Transactions []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// commits holds ≥ 2/3 pre-commit votes from the validator set.
	Commits       []*CommitVote `protobuf:"bytes,3,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetCommits() []*CommitVote {
	if x != nil {
		return x.Commits
	}
	return nil
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\x12\agxqs.v1\x1a\x11transaction.proto\"\xa3\x02\n" +
	"\vBlockHeader\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\fR\bparentId\x12\x1d\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fR\tstateRoot\x12\x17\n" +
	"\atx_root\x18\x05 \x01(\fR\x06txRoot\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12)\n" +
	"\x10proposer_address\x18\a \x01(\fR\x0fproposerAddress\x12\x14\n" +
	"\x05round\x18\b \x01(\rR\x05round\x12-\n" +
	"\x12proposer_signature\x18\t \x01(\fR\x11proposerSignature\"\xab\x01\n" +
	"\n" +
	"CommitVote\x12+\n" +
	"\x11validator_address\x18\x01 \x01(\fR\x10validatorAddress\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\fR\ablockId\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x12\x14\n" +
	"\x05round\x18\x04 \x01(\rR\x05round\x12'\n" +
	"\x03sig\x18\x05 \x01(\v2\x15.gxqs.v1.PQCSignatureR\x03sig\"\x9e\x01\n" +
	"\x05Block\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.gxqs.v1.BlockHeaderR\x06header\x128\n" +
	"\ftransactions\x18\x02 \x03(\v2\x14.gxqs.v1.TransactionR\ftransactions\x12-\n" +
	"\acommits\x18\x03 \x03(\v2\x13.gxqs.v1.CommitVoteR\acommitsB*Z(github.com/gxqs/core/proto/gen/v1;gxqsv1b\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_block_proto_goTypes = []any{
	(*BlockHeader)(nil),  // 0: gxqs.v1.BlockHeader
	(*CommitVote)(nil),   // 1: gxqs.v1.CommitVote
	(*Block)(nil),        // 2: gxqs.v1.Block
	(*PQCSignature)(nil), // 3: gxqs.v1.PQCSignature
	(*Transaction)(nil),  // 4: gxqs.v1.Transaction
}
var file_block_proto_depIdxs = []int32{
	3, // 0: gxqs.v1.CommitVote.sig:type_name -> gxqs.v1.PQCSignature
	0, // 1: gxqs.v1.Block.header:type_name -> gxqs.v1.BlockHeader
	4, // 2: gxqs.v1.Block.transactions:type_name -> gxqs.v1.Transaction
	1, // 3: gxqs.v1.Block.commits:type_name -> gxqs.v1.CommitVote
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	file_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
