// GXQS canonical transaction schema.
//
// This file is the SOURCE OF TRUTH for transaction wire format.
// Wallet and Exployer MUST consume this definition; they must NOT define their
// own transaction types.
//
// VERSIONING: field numbers are permanent.  New optional fields may be added
// with the next available field number.  Removing or renumbering fields
// requires a MAJOR version bump.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transaction.proto

package gxqsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignatureScheme identifies the post-quantum (or hybrid) algorithm used to
// produce a digital signature.
type SignatureScheme int32

const (
	SignatureScheme_SIGNATURE_SCHEME_UNSPECIFIED SignatureScheme = 0
	// ML-DSA-65 (NIST FIPS 204) — primary signing scheme.
	SignatureScheme_SIGNATURE_SCHEME_ML_DSA_65 SignatureScheme = 1
	// SLH-DSA-SHAKE-192s (NIST FIPS 205) — archival / high-value signing.
	SignatureScheme_SIGNATURE_SCHEME_SLH_DSA_192S SignatureScheme = 2
	// Hybrid Ed25519 + Dilithium2 — transitional, classical-compatible.
	SignatureScheme_SIGNATURE_SCHEME_HYBRID_ED_DIL2 SignatureScheme = 3
)

// Enum value maps for SignatureScheme.
var (
	SignatureScheme_name = map[int32]string{
		0: "SIGNATURE_SCHEME_UNSPECIFIED",
		1: "SIGNATURE_SCHEME_ML_DSA_65",
		2: "SIGNATURE_SCHEME_SLH_DSA_192S",
		3: "SIGNATURE_SCHEME_HYBRID_ED_DIL2",
	}
	SignatureScheme_value = map[string]int32{
		"SIGNATURE_SCHEME_UNSPECIFIED":    0,
		"SIGNATURE_SCHEME_ML_DSA_65":      1,
		"SIGNATURE_SCHEME_SLH_DSA_192S":   2,
		"SIGNATURE_SCHEME_HYBRID_ED_DIL2": 3,
	}
)

func (x SignatureScheme) Enum() *SignatureScheme {
	p := new(SignatureScheme)
	*p = x
	return p
}

func (x SignatureScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[0].Descriptor()
}

func (SignatureScheme) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[0]
}

func (x SignatureScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignatureScheme.Descriptor instead.
func (SignatureScheme) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

// PQCSignature is a scheme-tagged post-quantum (or hybrid) digital signature.
// The encoding of public_key and signature bytes is scheme-specific.
type PQCSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        SignatureScheme        `protobuf:"varint,1,opt,name=scheme,proto3,enum=gxqs.v1.SignatureScheme" json:"scheme,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PQCSignature) Reset() {
	*x = PQCSignature{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PQCSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PQCSignature) ProtoMessage() {}

func (x *PQCSignature) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PQCSignature.ProtoReflect.Descriptor instead.
func (*PQCSignature) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *PQCSignature) GetScheme() SignatureScheme {
	if x != nil {
		return x.Scheme
	}
	return SignatureScheme_SIGNATURE_SCHEME_UNSPECIFIED
}

func (x *PQCSignature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PQCSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Transaction is the canonical GXQS transaction envelope.
// All fields except sig are covered by the signing payload.
//
// Signing payload byte layout (deterministic, big-endian):
//
//	chain_id(8) || nonce(8) || from(32) || to(32) || value(8) ||
//	gas_limit(8) || gas_price(8) || timestamp(8) || data(variable)
type Transaction struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChainId uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce   uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// from is a 32-byte GXQS address derived from the sender's PQC public key.
	From []byte `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	// to is a 32-byte GXQS address.
	To []byte `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	// value is the native-token amount transferred (in the smallest denomination).
	Value uint64 `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	// data holds contract call data or arbitrary memo bytes.
	Data     []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	GasLimit uint64 `protobuf:"varint,7,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasPrice uint64 `protobuf:"varint,8,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// timestamp is a Unix millisecond timestamp set by the sender.
	Timestamp int64 `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// sig is the PQC signature over the signing payload.
	Sig           *PQCSignature `protobuf:"bytes,10,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Transaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Transaction) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Transaction) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Transaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Transaction) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *Transaction) GetGasPrice() uint64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetSig() *PQCSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\agxqs.v1\"}\n" +
	"\fPQCSignature\x120\n" +
	"\x06scheme\x18\x01 \x01(\x0e2\x18.gxqs.v1.SignatureSchemeR\x06scheme\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\x8d\x02\n" +
	"\vTransaction\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x12\n" +
	"\x04from\x18\x03 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\fR\x02to\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x04R\x05value\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x1b\n" +
	"\tgas_limit\x18\a \x01(\x04R\bgasLimit\x12\x1b\n" +
	"\tgas_price\x18\b \x01(\x04R\bgasPrice\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\x12'\n" +
	"\x03sig\x18\n" +
	" \x01(\v2\x15.gxqs.v1.PQCSignatureR\x03sig*\x9b\x01\n" +
	"\x0fSignatureScheme\x12 \n" +
	"\x1cSIGNATURE_SCHEME_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSIGNATURE_SCHEME_ML_DSA_65\x10\x01\x12!\n" +
	"\x1dSIGNATURE_SCHEME_SLH_DSA_192S\x10\x02\x12#\n" +
	"\x1fSIGNATURE_SCHEME_HYBRID_ED_DIL2\x10\x03B*Z(github.com/gxqs/core/proto/gen/v1;gxqsv1b\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transaction_proto_goTypes = []any{
	(SignatureScheme)(0), // 0: gxqs.v1.SignatureScheme
	(*PQCSignature)(nil), // 1: gxqs.v1.PQCSignature
	(*Transaction)(nil),  // 2: gxqs.v1.Transaction
}
var file_transaction_proto_depIdxs = []int32{
	0, // 0: gxqs.v1.PQCSignature.scheme:type_name -> gxqs.v1.SignatureScheme
	1, // 1: gxqs.v1.Transaction.sig:type_name -> gxqs.v1.PQCSignature
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		EnumInfos:         file_transaction_proto_enumTypes,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
